name: Package and Upload AWS Lambda Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package Lambda function
      run: |
        mkdir package
        pip install -r requirements.txt -t package/
        cp -r src/. package/

    - name: Archive Lambda function package
      run: |
        cd package
        zip -r ../lambda-function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Update Lambda function code
      run: |
        aws lambda update-function-configuration --function-name {{vars.AWS_LAMBDA_FN}} --environment "Variables={SDXL_SK=${{ secrets.SDXL_SK }},OPENAI_SK=${{ secrets.OPENAI_SK }}}"
        aws lambda update-function-code --function-name {{vars.AWS_LAMBDA_FN}} --zip-file fileb://lambda-function.zip
